services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - type: volume
        source: app-node_modules
        target: /usr/src/app/to-be-strong/node_modules
    # stdin_open: true
    tty: true
    command: ["npm", "run", "dev"] #npm run dev

volumes:
  app-node_modules:
    driver: local
    name: app-node_modules